### ISSUE TITLE
Setup failed for custom integration 'norwegiantide': Requirements for norwegiantide not found: ['matplotlib>=3.3.3'].

### ISSUE THREAD

**Issue by Howard0000** [tmjo/ha-norwegiantide#8]
Hi

I get this fault code after instaling HA update.
Setup failed for custom integration 'norwegiantide': Requirements for norwegiantide not found: ['matplotlib>=3.3.3'].

**Comment by tmjo** [comment]
Thanks for reporting. Assuming you updated to 2024.2 yesterday. I'll check.

**Comment by tmjo** [comment]
Just an update on this: Seems like this is a genereic HA/Matplotlib compatibility and that there is a solution soon to be implemented [here](https://github.com/home-assistant/core/pull/110706).

**Comment by tmjo** [comment]
The issue should be solved with the release of HA 2024.2.3. Please update Home Assistant and let me know if everthing looks good.

**Comment by paalj69** [comment]
Hi,
I still get an errormessage with the latest HA:
Logger: homeassistant.setup
Source: setup.py:221
First occurred: 24. februar 2024 kl. 12:11:39 (1 occurrences)
Last logged: 24. februar 2024 kl. 12:11:39

Setup failed for custom integration 'norwegiantide': Requirements for norwegiantide not found: ['matplotlib>=3.3.3'].

**Comment by Howard0000** [comment]
Hi.
Me too.
I still get the same errormessage with the latest HA.

**Comment by tmjo** [comment]
Hmm, that's strange. Are you both running HAOS too? It's working fine on my three instances. Do you have some more details on the error message, perhaps there is an additional issue.

**Comment by Howard0000** [comment]
Logger: homeassistant.util.package
Source: util/package.py:122
First occurred: 08:33:03 (3 occurrences)
Last logged: 08:34:44

Unable to install package matplotlib>=3.3.3: error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [123 lines of output] /tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:308: UserWarning: git archive did not support describe output warnings.warn("git archive did not support describe output") /tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:327: UserWarning: unprocessed git archival found (no export subst applied) warnings.warn("unprocessed git archival found (no export subst applied)") /tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py:90: UserWarning: version of matplotlib already set warnings.warn(f"version of {dist_name} already set") Edit mplsetup.cfg to change the build options; suppress output with --quiet. BUILDING MATPLOTLIB python: yes [3.12.1 (main, Jan 4 2024, 11:43:50) [GCC 13.2.1 20231014]] platform: yes [linux] tests: no [skipping due to configuration] macosx: no [Mac OS-X only] running egg_info writing lib/matplotlib.egg-info/PKG-INFO writing dependency_links to lib/matplotlib.egg-info/dependency_links.txt writing requirements to lib/matplotlib.egg-info/requires.txt writing top-level names to lib/matplotlib.egg-info/top_level.txt Traceback (most recent call last): File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/numpy/core/__init__.py", line 24, in <module> from . import multiarray File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/numpy/core/multiarray.py", line 10, in <module> from . import overrides File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/numpy/core/overrides.py", line 8, in <module> from numpy.core._multiarray_umath import ( ImportError: Error loading shared library /tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/numpy/core/_multiarray_umath.cpython-312-aarch64-linux-musl.so: Operation not permitted During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/numpy/__init__.py", line 130, in <module> from numpy.__config__ import show as show_config File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/numpy/__config__.py", line 4, in <module> from numpy.core._multiarray_umath import ( File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/numpy/core/__init__.py", line 50, in <module> raise ImportError(msg) ImportError: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.12 from "/usr/local/bin/python3" * The NumPy version is: "1.26.4" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: Error loading shared library /tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/numpy/core/_multiarray_umath.cpython-312-aarch64-linux-musl.so: Operation not permitted The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module> main() File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires self.run_setup() File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup exec(code, locals()) File "<string>", line 279, in <module> File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command super().run_command(command) File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run self.find_sources() File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources mm.run() File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run self.add_defaults() File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults sdist.add_defaults(self) File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults super().add_defaults() File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults self._add_defaults_ext() File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext build_ext = self.get_finalized_command('build_ext') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command cmd_obj.ensure_finalized() File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized self.finalize_options() File "<string>", line 80, in finalize_options File "/tmp/pip-install-6nn60nn1/matplotlib_15fc5e759af34c879975aea84fc64053/setupext.py", line 403, in get_extensions add_numpy_flags(ext) File "/tmp/pip-install-6nn60nn1/matplotlib_15fc5e759af34c879975aea84fc64053/setupext.py", line 511, in add_numpy_flags import numpy as np File "/tmp/pip-build-env-2ibxs3n3/overlay/lib/python3.12/site-packages/numpy/__init__.py", line 135, in <module> raise ImportError(msg) from e ImportError: Error importing numpy: you should not try to import numpy from its source directory; please exit the numpy source tree, and relaunch your python interpreter from there. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.
Unable to install package matplotlib>=3.3.3: error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [123 lines of output] /tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:308: UserWarning: git archive did not support describe output warnings.warn("git archive did not support describe output") /tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:327: UserWarning: unprocessed git archival found (no export subst applied) warnings.warn("unprocessed git archival found (no export subst applied)") /tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py:90: UserWarning: version of matplotlib already set warnings.warn(f"version of {dist_name} already set") Edit mplsetup.cfg to change the build options; suppress output with --quiet. BUILDING MATPLOTLIB python: yes [3.12.1 (main, Jan 4 2024, 11:43:50) [GCC 13.2.1 20231014]] platform: yes [linux] tests: no [skipping due to configuration] macosx: no [Mac OS-X only] running egg_info writing lib/matplotlib.egg-info/PKG-INFO writing dependency_links to lib/matplotlib.egg-info/dependency_links.txt writing requirements to lib/matplotlib.egg-info/requires.txt writing top-level names to lib/matplotlib.egg-info/top_level.txt Traceback (most recent call last): File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/numpy/core/__init__.py", line 24, in <module> from . import multiarray File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/numpy/core/multiarray.py", line 10, in <module> from . import overrides File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/numpy/core/overrides.py", line 8, in <module> from numpy.core._multiarray_umath import ( ImportError: Error loading shared library /tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/numpy/core/_multiarray_umath.cpython-312-aarch64-linux-musl.so: Operation not permitted During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/numpy/__init__.py", line 130, in <module> from numpy.__config__ import show as show_config File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/numpy/__config__.py", line 4, in <module> from numpy.core._multiarray_umath import ( File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/numpy/core/__init__.py", line 50, in <module> raise ImportError(msg) ImportError: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.12 from "/usr/local/bin/python3" * The NumPy version is: "1.26.4" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: Error loading shared library /tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/numpy/core/_multiarray_umath.cpython-312-aarch64-linux-musl.so: Operation not permitted The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module> main() File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires self.run_setup() File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup exec(code, locals()) File "<string>", line 279, in <module> File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command super().run_command(command) File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run self.find_sources() File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources mm.run() File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run self.add_defaults() File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults sdist.add_defaults(self) File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults super().add_defaults() File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults self._add_defaults_ext() File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext build_ext = self.get_finalized_command('build_ext') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command cmd_obj.ensure_finalized() File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized self.finalize_options() File "<string>", line 80, in finalize_options File "/tmp/pip-install-p3otu6q6/matplotlib_785898191fd344b08c6ce6e8e870fade/setupext.py", line 403, in get_extensions add_numpy_flags(ext) File "/tmp/pip-install-p3otu6q6/matplotlib_785898191fd344b08c6ce6e8e870fade/setupext.py", line 511, in add_numpy_flags import numpy as np File "/tmp/pip-build-env-ay6hi8nm/overlay/lib/python3.12/site-packages/numpy/__init__.py", line 135, in <module> raise ImportError(msg) from e ImportError: Error importing numpy: you should not try to import numpy from its source directory; please exit the numpy source tree, and relaunch your python interpreter from there. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.
Unable to install package matplotlib>=3.3.3: error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [123 lines of output] /tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:308: UserWarning: git archive did not support describe output warnings.warn("git archive did not support describe output") /tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:327: UserWarning: unprocessed git archival found (no export subst applied) warnings.warn("unprocessed git archival found (no export subst applied)") /tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py:90: UserWarning: version of matplotlib already set warnings.warn(f"version of {dist_name} already set") Edit mplsetup.cfg to change the build options; suppress output with --quiet. BUILDING MATPLOTLIB python: yes [3.12.1 (main, Jan 4 2024, 11:43:50) [GCC 13.2.1 20231014]] platform: yes [linux] tests: no [skipping due to configuration] macosx: no [Mac OS-X only] running egg_info writing lib/matplotlib.egg-info/PKG-INFO writing dependency_links to lib/matplotlib.egg-info/dependency_links.txt writing requirements to lib/matplotlib.egg-info/requires.txt writing top-level names to lib/matplotlib.egg-info/top_level.txt Traceback (most recent call last): File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/numpy/core/__init__.py", line 24, in <module> from . import multiarray File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/numpy/core/multiarray.py", line 10, in <module> from . import overrides File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/numpy/core/overrides.py", line 8, in <module> from numpy.core._multiarray_umath import ( ImportError: Error loading shared library /tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/numpy/core/_multiarray_umath.cpython-312-aarch64-linux-musl.so: Operation not permitted During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/numpy/__init__.py", line 130, in <module> from numpy.__config__ import show as show_config File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/numpy/__config__.py", line 4, in <module> from numpy.core._multiarray_umath import ( File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/numpy/core/__init__.py", line 50, in <module> raise ImportError(msg) ImportError: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.12 from "/usr/local/bin/python3" * The NumPy version is: "1.26.4" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: Error loading shared library /tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/numpy/core/_multiarray_umath.cpython-312-aarch64-linux-musl.so: Operation not permitted The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module> main() File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires self.run_setup() File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup exec(code, locals()) File "<string>", line 279, in <module> File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command super().run_command(command) File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run self.find_sources() File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources mm.run() File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run self.add_defaults() File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults sdist.add_defaults(self) File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults super().add_defaults() File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults self._add_defaults_ext() File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext build_ext = self.get_finalized_command('build_ext') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command cmd_obj.ensure_finalized() File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized self.finalize_options() File "<string>", line 80, in finalize_options File "/tmp/pip-install-2ugx67va/matplotlib_50392323b6f74e818bd7587e3e9dd83c/setupext.py", line 403, in get_extensions add_numpy_flags(ext) File "/tmp/pip-install-2ugx67va/matplotlib_50392323b6f74e818bd7587e3e9dd83c/setupext.py", line 511, in add_numpy_flags import numpy as np File "/tmp/pip-build-env-6kmhs6_b/overlay/lib/python3.12/site-packages/numpy/__init__.py", line 135, in <module> raise ImportError(msg) from e ImportError: Error importing numpy: you should not try to import numpy from its source directory; please exit the numpy source tree, and relaunch your python interpreter from there. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Howard0000** [comment]
Logger: homeassistant.setup
Source: setup.py:221
First occurred: 08:34:44 (1 occurrences)
Last logged: 08:34:44

Setup failed for custom integration 'norwegiantide': Requirements for norwegiantide not found: ['matplotlib>=3.3.3'].

**Comment by TinkerThor** [comment]
Same here. Latest 2024.2.4

**Comment by tmjo** [comment]
Thanks for the log. It is different from what I saw last week, now it seems like it is Numpy that's complained about. Probably some mismatch between matplotlib, numpy and HA/Python3.12. I'm sure we'll figure out this somehow, but it may take some time.

If some of you are feeling lucky or experimental, it is possible to do adjustments in [manifest.json](https://github.com/tmjo/ha-norwegiantide/blob/main/custom_components/norwegiantide/manifest.json) on your local installation and see if it resolves things. Specifically is the combination in
`
"requirements": ["Pillow>=8.1.0", "matplotlib>=3.3.3","numpy>=1.21.6"]
`
Matplotlib used to be pinned at 3.3.3 in HA, but that was removed with HA 2024.2.3.

**Comment by tmjo** [comment]
I just updated one of my instances to 2024.2.4, latest supervisor and OS. It is still working on my side. If some of you are comfortable with using the SSH addon, disable protection mode, enter the right docker container by typing `docker exec -ti homeassistant bash` and then `pip list | grep numpy` and `pip list | grep matplotlib` to check versions (if any) are installed of matplotlib and numpy.

**Comment by Howard0000** [comment]
numpy 1.26.0
matplotlib no result

**Comment by tmjo** [comment]
> numpy 1.26.0 matplotlib no result

Thanks. Would you be ok with experimenting with the setting? Hard for me to troubleshoot since it is already working. I've got numpy 1.26.0 installed with matplotlib 3.8.3, the below change to manifest.json will pin the matplotlib version to the same as I have. Remember to restart HA after the change is done.
`
"requirements": ["Pillow>=8.1.0", "matplotlib==3.8.3","numpy>=1.26.0"]
`

**Comment by paalj69** [comment]
Hi,
I changed the requirements and got this fault:
Logger: homeassistant.setup
Source: setup.py:221
First occurred: 09:13:36 (1 occurrences)
Last logged: 09:13:36

Setup failed for custom integration 'norwegiantide': Requirements for norwegiantide not found: ['matplotlib==3.8.3'].

**Comment by tmjo** [comment]
> Setup failed for custom integration 'norwegiantide': Requirements for norwegiantide not found: ['matplotlib==3.8.3'].

Thanks for trying. I am not sure what is going on, and really not why it works in some systems and not in others. Could be worth a try to test matplotlib >=3.8.3 instead. @paalj69  did you check installed versions and got 'no result' too? I guess the >= would only make sense if other integrations require a newer version, but does not seem to be the case for @Howard0000 since it says 'no result'.

My best guess is that there is a mismatch with numpy (that seems to be pinned in HA just like matplotlib was) and other libraries, but I am not an expert on this. I'll pay attention and see if anything changes in HA, it seems to be affecting other custom integrations too.

**Comment by tmjo** [comment]
Guys, which hardware are you running HA on?

**Comment by Howard0000** [comment]
I`am running Ha on RPI 4.

**Comment by paalj69** [comment]
Hi,
Yes, same result as Howard0000. No, matplotlib....
Also running HA on rpi4

**Comment by tmjo** [comment]
I've opened an issue over at HA to [request help](https://github.com/home-assistant/core/issues/111732).

**Comment by paalj69** [comment]
Just to make it clear. The terminal response is like this:
<img width="276" alt="Skjermbilde 2024-02-29 083449" src="https://github.com/tmjo/ha-norwegiantide/assets/76810835/68530012-3ab8-4eb1-93c1-b6d149296958">

**Comment by gunmalmg** [comment]
Hi
Thank you for a great integration. Very useful 

I have several HA installations (In my house - in my cottage)
The integration function well on my Intel NUC installation - at home , but it fails unfortunately on my RPi 4 installation at my cottage by the sea. 

I am running same versions of HA om both installations :

Core
2024.4.4
Supervisor
2024.04.0
Operating System
12.2
Frontend
20240404.2

Here is the error log from the RPi 4 installation : 

Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 22:28:15 (3 occurrences)
Last logged: 22:30:04

Unable to install package matplotlib>=3.3.3: error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [123 lines of output] /tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:308: UserWarning: git archive did not support describe output warnings.warn("git archive did not support describe output") /tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:327: UserWarning: unprocessed git archival found (no export subst applied) warnings.warn("unprocessed git archival found (no export subst applied)") /tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py:90: UserWarning: version of matplotlib already set warnings.warn(f"version of {dist_name} already set") Edit mplsetup.cfg to change the build options; suppress output with --quiet. BUILDING MATPLOTLIB python: yes [3.12.2 (main, Mar 18 2024, 23:18:19) [GCC 13.2.1 20231014]] platform: yes [linux] tests: no [skipping due to configuration] macosx: no [Mac OS-X only] running egg_info writing lib/matplotlib.egg-info/PKG-INFO writing dependency_links to lib/matplotlib.egg-info/dependency_links.txt writing requirements to lib/matplotlib.egg-info/requires.txt writing top-level names to lib/matplotlib.egg-info/top_level.txt Traceback (most recent call last): File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/numpy/_core/__init__.py", line 23, in <module> from . import multiarray File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/numpy/_core/multiarray.py", line 10, in <module> from . import overrides File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/numpy/_core/overrides.py", line 8, in <module> from numpy._core._multiarray_umath import ( ImportError: Error loading shared library /tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-aarch64-linux-musl.so: Operation not permitted During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/numpy/__init__.py", line 114, in <module> from numpy.__config__ import show as show_config File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/numpy/__config__.py", line 4, in <module> from numpy._core._multiarray_umath import ( File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/numpy/_core/__init__.py", line 49, in <module> raise ImportError(msg) ImportError: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.12 from "/usr/local/bin/python3" * The NumPy version is: "2.0.0rc1" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: Error loading shared library /tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-aarch64-linux-musl.so: Operation not permitted The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module> main() File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires self.run_setup() File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup exec(code, locals()) File "<string>", line 279, in <module> File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands dist.run_commands() File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command super().run_command(command) File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run self.find_sources() File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources mm.run() File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run self.add_defaults() File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults sdist.add_defaults(self) File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults super().add_defaults() File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults self._add_defaults_ext() File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 334, in _add_defaults_ext build_ext = self.get_finalized_command('build_ext') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 303, in get_finalized_command cmd_obj.ensure_finalized() File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized self.finalize_options() File "<string>", line 80, in finalize_options File "/tmp/pip-install-1_r69vwd/matplotlib_17987d41ad284cc99f00ef539377194e/setupext.py", line 403, in get_extensions add_numpy_flags(ext) File "/tmp/pip-install-1_r69vwd/matplotlib_17987d41ad284cc99f00ef539377194e/setupext.py", line 511, in add_numpy_flags import numpy as np File "/tmp/pip-build-env-v8klr1t_/overlay/lib/python3.12/site-packages/numpy/__init__.py", line 119, in <module> raise ImportError(msg) from e ImportError: Error importing numpy: you should not try to import numpy from its source directory; please exit the numpy source tree, and relaunch your python interpreter from there. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.
Unable to install package matplotlib>=3.3.3: error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [123 lines of output] /tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:308: UserWarning: git archive did not support describe output warnings.warn("git archive did not support describe output") /tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:327: UserWarning: unprocessed git archival found (no export subst applied) warnings.warn("unprocessed git archival found (no export subst applied)") /tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py:90: UserWarning: version of matplotlib already set warnings.warn(f"version of {dist_name} already set") Edit mplsetup.cfg to change the build options; suppress output with --quiet. BUILDING MATPLOTLIB python: yes [3.12.2 (main, Mar 18 2024, 23:18:19) [GCC 13.2.1 20231014]] platform: yes [linux] tests: no [skipping due to configuration] macosx: no [Mac OS-X only] running egg_info writing lib/matplotlib.egg-info/PKG-INFO writing dependency_links to lib/matplotlib.egg-info/dependency_links.txt writing requirements to lib/matplotlib.egg-info/requires.txt writing top-level names to lib/matplotlib.egg-info/top_level.txt Traceback (most recent call last): File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/numpy/_core/__init__.py", line 23, in <module> from . import multiarray File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/numpy/_core/multiarray.py", line 10, in <module> from . import overrides File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/numpy/_core/overrides.py", line 8, in <module> from numpy._core._multiarray_umath import ( ImportError: Error loading shared library /tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-aarch64-linux-musl.so: Operation not permitted During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/numpy/__init__.py", line 114, in <module> from numpy.__config__ import show as show_config File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/numpy/__config__.py", line 4, in <module> from numpy._core._multiarray_umath import ( File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/numpy/_core/__init__.py", line 49, in <module> raise ImportError(msg) ImportError: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.12 from "/usr/local/bin/python3" * The NumPy version is: "2.0.0rc1" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: Error loading shared library /tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-aarch64-linux-musl.so: Operation not permitted The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module> main() File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires self.run_setup() File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup exec(code, locals()) File "<string>", line 279, in <module> File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands dist.run_commands() File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command super().run_command(command) File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run self.find_sources() File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources mm.run() File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run self.add_defaults() File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults sdist.add_defaults(self) File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults super().add_defaults() File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults self._add_defaults_ext() File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 334, in _add_defaults_ext build_ext = self.get_finalized_command('build_ext') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 303, in get_finalized_command cmd_obj.ensure_finalized() File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized self.finalize_options() File "<string>", line 80, in finalize_options File "/tmp/pip-install-6j6dr8b0/matplotlib_2abac3247b2e4a579c70f6b79dddd2c5/setupext.py", line 403, in get_extensions add_numpy_flags(ext) File "/tmp/pip-install-6j6dr8b0/matplotlib_2abac3247b2e4a579c70f6b79dddd2c5/setupext.py", line 511, in add_numpy_flags import numpy as np File "/tmp/pip-build-env-qjrsr8sq/overlay/lib/python3.12/site-packages/numpy/__init__.py", line 119, in <module> raise ImportError(msg) from e ImportError: Error importing numpy: you should not try to import numpy from its source directory; please exit the numpy source tree, and relaunch your python interpreter from there. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.
Unable to install package matplotlib>=3.3.3: error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [123 lines of output] /tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:308: UserWarning: git archive did not support describe output warnings.warn("git archive did not support describe output") /tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:327: UserWarning: unprocessed git archival found (no export subst applied) warnings.warn("unprocessed git archival found (no export subst applied)") /tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py:90: UserWarning: version of matplotlib already set warnings.warn(f"version of {dist_name} already set") Edit mplsetup.cfg to change the build options; suppress output with --quiet. BUILDING MATPLOTLIB python: yes [3.12.2 (main, Mar 18 2024, 23:18:19) [GCC 13.2.1 20231014]] platform: yes [linux] tests: no [skipping due to configuration] macosx: no [Mac OS-X only] running egg_info writing lib/matplotlib.egg-info/PKG-INFO writing dependency_links to lib/matplotlib.egg-info/dependency_links.txt writing requirements to lib/matplotlib.egg-info/requires.txt writing top-level names to lib/matplotlib.egg-info/top_level.txt Traceback (most recent call last): File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/numpy/_core/__init__.py", line 23, in <module> from . import multiarray File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/numpy/_core/multiarray.py", line 10, in <module> from . import overrides File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/numpy/_core/overrides.py", line 8, in <module> from numpy._core._multiarray_umath import ( ImportError: Error loading shared library /tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-aarch64-linux-musl.so: Operation not permitted During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/numpy/__init__.py", line 114, in <module> from numpy.__config__ import show as show_config File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/numpy/__config__.py", line 4, in <module> from numpy._core._multiarray_umath import ( File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/numpy/_core/__init__.py", line 49, in <module> raise ImportError(msg) ImportError: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.12 from "/usr/local/bin/python3" * The NumPy version is: "2.0.0rc1" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: Error loading shared library /tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/numpy/_core/_multiarray_umath.cpython-312-aarch64-linux-musl.so: Operation not permitted The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module> main() File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires self.run_setup() File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup exec(code, locals()) File "<string>", line 279, in <module> File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands dist.run_commands() File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command super().run_command(command) File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run self.find_sources() File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources mm.run() File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run self.add_defaults() File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults sdist.add_defaults(self) File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults super().add_defaults() File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults self._add_defaults_ext() File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 334, in _add_defaults_ext build_ext = self.get_finalized_command('build_ext') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 303, in get_finalized_command cmd_obj.ensure_finalized() File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized self.finalize_options() File "<string>", line 80, in finalize_options File "/tmp/pip-install-0odx1i6b/matplotlib_1b41e61b0007442087c5ce70de707d39/setupext.py", line 403, in get_extensions add_numpy_flags(ext) File "/tmp/pip-install-0odx1i6b/matplotlib_1b41e61b0007442087c5ce70de707d39/setupext.py", line 511, in add_numpy_flags import numpy as np File "/tmp/pip-build-env-3xd8u632/overlay/lib/python3.12/site-packages/numpy/__init__.py", line 119, in <module> raise ImportError(msg) from e ImportError: Error importing numpy: you should not try to import numpy from its source directory; please exit the numpy source tree, and relaunch your python interpreter from there. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by tmjo** [comment]
Hi,

Yes, mine is running fine on NUC too. Ref [this](https://github.com/home-assistant/core/issues/111732), it seems there is a incompatibility with current version of Matplotlib and Rpi. So far no support over at HA.




> Hi Thank you for a great integration. Very useful
> 
> I have several HA installations (In my house - in my cottage) The integration function well on my Intel NUC installation - at home , but it fails unfortunately on my RPi 4 installation at my cottage by the sea.
>

**Comment by cortado** [comment]
Still no response from HAOS issue, regarding RPi incompatibility? having same problem at my cottage, where I actually used it actively... Could a solution be a version without Matplotlib, that would support only using Apexcharts for visualization?

**Comment by tmjo** [comment]
@cortado; yes, I have been thinking the same. I'll see if I can solve that.

**Comment by gunmalmg** [comment]
That would be great!  👍

**Comment by cortado** [comment]
fantastic! 
also: does anyone of you experts have some apexcharts setup you could share?

**Comment by cortado** [comment]
> @cortado; yes, I have been thinking the same. I'll see if I can solve that.

Have you been able to look at this, and possibly see a way towards solution?

**Comment by DTekNOdev** [comment]
If anyone is still struggling with this I have a modified fork of the integration that does not rely on matplotlib. Apex charts can be used for graphing the data:

https://github.com/jm-cook/ha-norwegiantide-lite

<img width="523" height="479" alt="Image" src="https://github.com/user-attachments/assets/c129bf3a-1b16-4467-8cbd-9f2635792b11" />
